list(APPEND Libevent_INCLUDE_PATHS "$ENV{HOME}/include")
list(APPEND Libevent_LIB_PATHS "$ENV{HOME}/lib")

find_path(LIBEVENT_INCLUDE_DIR event.h PATHS ${Libevent_INCLUDE_PATHS})
find_library(LIBEVENT_LIBRARY NAMES event PATHS ${Libevent_LIB_PATHS})

#FIND_LIBRARY(LIBEVENT_LIBRARY NAMES event PATHS ${LibEvent_LIB_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(LIBEVENT_CORE_LIBRARY NAMES event_core PATHS ${LibEvent_LIB_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(LIBEVENT_PTHREADS_LIBRARY NAMES event_pthreads PATHS ${LibEvent_LIB_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(LIBEVENT_EXTRA_LIBRARY NAMES event_extra PATHS ${LibEvent_LIB_PATHS} NO_DEFAULT_PATH)
#FIND_LIBRARY(LIBEVENT_OPENSSL_LIBRARY NAMES event_openssl PATHS ${LibEvent_LIB_PATHS} NO_DEFAULT_PATH)


include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Libevent DEFAULT_MSG LIBEVENT_LIBRARY LIBEVENT_INCLUDE_DIR)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEventPthreads DEFAULT_MSG LIBEVENT_PTHREADS_LIBRARY LIBEVENT_INCLUDE_DIR)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEventCore DEFAULT_MSG LIBEVENT_CORE_LIBRARY LIBEVENT_INCLUDE_DIR)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEventExtra DEFAULT_MSG LIBEVENT_EXTRA_LIBRARY LIBEVENT_INCLUDE_DIR)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEventOpenssl DEFAULT_MSG LIBEVENT_OPENSSL_LIBRARY LIBEVENT_INCLUDE_DIR)

mark_as_advanced(
    LIBEVENT_INCLUDE_DIR 
    LIBEVENT_LIBRARY 
    #LIBEVENT_PTHREADS_LIBRARY 
    #LIBEVENT_OPENSSL_LIBRARY 
    #LIBEVENT_CORE_LIBRARY 
    #LIBEVENT_EXTRA_LIBRARY
)
